# Default values for the Helm chart
webhook:
  url: "" # Required
  token: "" # Required

image:
  repository: "" # Required
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

filterConfig:
  enabled: false
  filters:
    - problemType: "Malfunction"
      entityType: "Pod"