image:
  repository: us-docker.pkg.dev/public-causely/public/bot
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

auth:
  token: "" # Required

webhooks:
  - name: "" # Required
    url: "" # Required
    token: ""
    filters:
      enabled: true
      values:
        - field: "impactsSLO"
          operator: "equals"
          value: True