image:
  repository: "" # Required
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

auth:
  token: "" # Required

webhooks:
  - name: "" # Required
    url: "" # Required
    token: ""
    filters:
      enabled: true
      values:
        - field: "impactsSLO"
          operator: "equals"
          value: True