{{- include "validateWebhookUrl" . -}}
{{- include "validateBearerToken" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: causelybot-secret
type: Opaque
data:
  webhook-url: {{ .Values.webhook.url | b64enc }}
  token: {{ .Values.webhook.token | b64enc }}