apiVersion: v1
kind: ConfigMap
metadata:
  name: causelybot-config
data:
  config.yaml: |
    filterConfig:
      enabled: {{ .Values.filterConfig.enabled | default false }}
      filters:
        {{- range .Values.filterConfig.filters }}
        - problemType: "{{ .problemType }}"
          entityType: "{{ .entityType }}"
        {{- end }}