apiVersion: v1
kind: ConfigMap
metadata:
  name: causelybot-config
data:
  config.yaml: |
    webhooks:
      {{- range .Values.webhooks }}
      - name: "{{ .name }}"
        filters:
          enabled: {{ if hasKey . "filters" }}{{ .filters.enabled | default false }}{{ else }}false{{ end }}
          values:{{ if and (hasKey . "filters") (hasKey .filters "values") }}
            {{ toYaml .filters.values | nindent 12 }}
          {{ else }} []
          {{ end }}
      {{- end }}