{{- include "validateWebhookUrl" . -}}
{{- include "validateBearerToken" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace:  {{ .Release.Namespace }}
type: Opaque
data:
  webhook-url: {{ .Values.webhook.url | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: bearer-token-secret
  namespace:  {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.webhook.token | b64enc }}