{{- include "validateImageRepository" . -}}
{{- include "validateWebhooks" . -}}
{{- include "validateAuthToken" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: causelybot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: causelybot
  template:
    metadata:
      labels:
        app: causelybot
    spec:
      containers:
      - name: causelybot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        env:
        # Global Auth Token for bot to authenticate with executor
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: causelybot-auth-secret
              key: token
        
        # Webhook environment variables (URL and TOKEN for each webhook)
        {{- range .Values.webhooks }}
        - name: URL_{{ .name | upper | replace " " "_" }}
          valueFrom:
            secretKeyRef:
              name: causelybot-secret-{{ .name | lower | replace " " "-" }}
              key: webhook-url
        - name: TOKEN_{{ .name | upper | replace " " "_" }}
          valueFrom:
            secretKeyRef:
              name: causelybot-secret-{{ .name | lower | replace " " "-" }}
              key: token
        {{- end }}
        
        resources:
          limits:
            cpu: "1.0"
            memory: "512Mi"
          requests:
            cpu: "1.0"
            memory: "256Mi"
        volumeMounts:
        - name: config
          mountPath: /etc/causelybot
      volumes:
      - name: config
        configMap:
          name: causelybot-config
