{{- include "validateAuthToken" . -}}
{{- include "validateWebhooks" . -}}

# Global Auth Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: causelybot-auth-secret
type: Opaque
data:
  token: {{ .Values.auth.token | default "" | b64enc }}

# Webhook Secrets (one per webhook)
{{- range .Values.webhooks }}
---
apiVersion: v1
kind: Secret
metadata:
  name: causelybot-secret-{{ .name | lower | replace " " "-" }}
type: Opaque
data:
  webhook-url: {{ .url | default "" | b64enc }}
  token: {{ .token | default "" | b64enc }}
{{- end }}
